[package]
name = "nomicon"
version = "0.1.0"
authors = ["0xE8551CCB"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
